### ISSUE TITLE
Gateway Issue - No gateway found!

### ISSUE THREAD

**Issue by ChandaniPatel412** [maikvandergaag/msft-extensions#292]
Hi, I am trying to update gateway using Power BI Action extension. 

```
    - task: PowerBIActions@5
      inputs:
        PowerBIServiceEndpoint: '<<service principle>>'
        Action: 'UpdateGateway'
        WorkspaceName: '$(PowerBIWorkspace)'
        DatasetName: '<<Dataset name>>'
        GatewayName: '$(PowerBIGateway)'
```

I am getting below error. 
No gateway found! Ensure MasterAccount authentication is used and check if specified gateway 'name of gateway'  is valid and present.

I can confirm gateway exists with the same name I am passing in YAML. Can someone please guide?
