### ISSUE TITLE
PowerBI Actions Extension - Link to Wiki broken?

### ISSUE THREAD

**Issue by SA-accesso** [maikvandergaag/msft-extensions#493]
PowerBI extension readme points to this wiki link https://github.com/MaikvanderGaag/msft-extensions/wiki

Yet the documentation for the extension is not there.

Currently struggling to delete workspaces using this extension:

```
  steps:
  - checkout: none
  - task: PowerBIActions@5
    inputs:
      PowerBIServiceEndpoint: 'powerbi-shareduk01'
      Action: 'DeleteWorkspace'
      WorkspaceName: '*blduk01*'
```

Logging suggests it's working but I can still see the workspaces there:

```
Starting: PowerBIActions
==============================================================================
Task         : Power BI Actions
Description  : Release Task Power BI Actions
Version      : 5.4.44
Author       : Maik van der Gaag
Help         : 
==============================================================================
Starting Power BI Actions extension
### Required Module is needed. Importing now...
### Trying to import the incorporated module for PowerBI
Deleting a Workspace
Workspace: *blduk01* does exist
Done processing Power BI Actions
Done running Power BI Actions extension.
Finishing: PowerBIActions
```

Please advise. 

Thanks
