### ISSUE TITLE
Problems with dots in pbix file name (*2024.01.22 - my name.pbix*)

### ISSUE THREAD

**Issue by michelmetran** [maikvandergaag/msft-extensions#523]
**Describe the issue**
I am using the extension to upload pbix files.

I noticed that when the file has a dot in the middle of the filename, it gives an error and the upload modifies the name truncating at the first dot.

If the file is named *2024.01.22 - my name.pbix*, at the workspace will be *2024.01*.

![](https://i.imgur.com/pbH4ylo.png)

<br>

----

**Extension**
 - Extension: [Power BI Actions](https://marketplace.visualstudio.com/items?itemName=maikvandergaag.maikvandergaag-power-bi-actions)
 - Version: 5.4.44

<br>

----

**To Reproduce**
I maintain my repositories with azure-pipelines.yml file with the following content to perform the steps of creating artifact and publishing

```yaml
# Pipeline criado para automatizar a publicação de
# arquivos .pbix em workspaces do Power BI
#
# Michel Metran
# Data: 05.10.2023
# Atualizado em: 22.01.2024
# -------------------------

trigger:
  - main

# Agent
pool:
  vmImage: windows-2019
  

# Parâmetros
parameters:
  - name: BI2Workspace
    type: object
    default:
      - NamePbixFile: '2024.01.22 - ANPPs.pbix'
        WorkspaceName: 'CTIC - old'
     
        
# Variáveis
variables:
  # Set Service
  PowerBIService: 'service-principal'

  # Debugar Pipeline
  system.debug: 'true'

steps:
  # Loop
  # https://igeorgiev.eu/devops/azure-pipelines-use-each-loop/
  - ${{ each params in parameters.BI2Workspace }}:
    
    # Copia o arquivo .pbix para Staging Directory
    - task: CopyFiles@2
      displayName: 'Copy Files to: "$(Build.ArtifactStagingDirectory)"'
      inputs:
        SourceFolder: $(Build.SourcesDirectory)
        Contents: '**/${{ params.NamePbixFile }}'
        TargetFolder: $(Build.ArtifactStagingDirectory)
        flattenFolders: true
        OverWrite: true

    # Publica arquivo do Staging Directory no Artifact
    # https://learn.microsoft.com/pt-br/azure/devops/pipelines/tasks/reference/publish-build-artifacts-v1
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact to: $(Build.ArtifactStagingDirectory)'
      inputs:
        PathtoPublish: $(Build.ArtifactStagingDirectory)
        ArtifactName: my_artifact
        publishLocation: Container
        MaxArtifactSize: 0
        Parallel: false
        StoreAsTar: false

    # Publica Artifact na workspace
    - task: maikvandergaag.maikvandergaag-power-bi-actions.PowerBIActions.PowerBIActions@5
      displayName: 'Power BI: Publish in Workspace'
      inputs:
        PowerBIServiceEndpoint: '${{ variables.PowerBIService }}'
        WorkspaceName: '${{ params.WorkspaceName }}'
        PowerBIPath: '$(System.ArtifactsDirectory)/${{ params.NamePbixFile }}'
```

<br>

----

**Expected behavior**

Publish with the correct name.

<br>

----

**Situation**

 - Agent type: windows-2019
 - Autentication: Service Principal

<br>

----

**Log info**
[log.txt](https://github.com/maikvandergaag/msft-extensions/files/14016911/log.txt)

<br>

----

**Additional information**

I noticed that if I try to upload with powershell, uploading with pbix does not change the name.

```shell
New-PowerBIReport -WorkspaceId 3eb21cbd-bca42 -Path 'C:\Users\user\bi_anpp\bi\versions\2024.01.22 - ANPPs.pbix'
```
