### ISSUE TITLE
Unable to Change the data sources and Update Parameter using Power BI Actions 

### ISSUE THREAD

**Issue by nikmk05** [maikvandergaag/msft-extensions#545]
We are working on CICD Pipeline using Power BI Actions in Azure DevOps.

<img width="434" alt="cicd" src="https://github.com/maikvandergaag/msft-extensions/assets/121431424/c0abc0a8-733c-4f82-81d0-fdb20323fa05">

 We created release pipeline using Power BI Actions, we got the output for Publishing, adding user, creating workspaces.
But 
for our case, we have 2 environments, Dev and Test.

We are using SQL Server as Datasource. 
we have 2 databases DEV_Database for DEV environment and Test_Database for Test environment.
As of now, we are using DEV_database for developing reports. 
We are trying to publish the report from DEV to Test workspaces. We need to use Test_database in Test workspace. Therefore, we are trying to do this using parameters. But Power Bi actions showing "Bad request " and "Invalidstatus " like this.

Please consider this request and help me to find the solution.

Thanks.

**Comment by pphidev** [comment]
Hi @nikmk05,

Can you provide more details on the settings that you use for the release pipeline?

Example if you use the Power BI Actions in a yml file:
```yml
- task: PowerBIActions@5
   displayName: 'Update parameters'
   inputs:
      PowerBIServiceEndpoint: ${{ variables.serviceConnection }}
      Action: 'UpdateParameters'
      WorkspaceName: ${{ variables.powerbiWorkspace }}
      DatasetName: ${{ variables.dataSetName }}
      ParameterInput: '[{"name":"Environment","newValue":"${{ parameters.env }}"}]'
```

In above example, the parameter `env` stores the reference to the environment (e.g. `dev`, `acc`, `test` etc.).

Kind regards,

Pim
