### ISSUE TITLE
Power BI Actions: Set username and password for DQ datasources

### ISSUE THREAD

**Issue by AlexandrStadolnik** [maikvandergaag/msft-extensions#83]
Good day, Maik. 

Could you introduce the actions again, as you proposed in the review?
Ability to set username and password for DQ datasources is really missing in this extension.

Thank you

**Comment by maikvandergaag** [comment]
I marked the issue as feature request and will check when I will be able to add it again.

**Comment by AlexandrStadolnik** [comment]
Thank you very much. Looking forward for the updates.

**Comment by Singley** [comment]
@maikvandergaag @AlexandrStadolnik is this feature request encompassing of setting the SQL credentials?  For example, I have confirmed that I can update my Data Source connection using the 'UpdateDataSource' operation in this extension.  However, I cannot set the credentials on that same data set during the same operation.  This leads to the following workflow:

1. Deploy the Power BI report via Devops, updating the DataSource Connection at the same time.  This uses a Service Account.  At this time, my report cannot refresh, as the dataset credentials are invalid.  
2. Update the dataset credentials after logging on the portal with the Service Account
3. The previous step must be done using the Service Account or I have to take ownership with my ID.  If I take ownership away from the Service Account, the 'UpdateDataSource' operation fails on the next deployment.
![image](https://user-images.githubusercontent.com/29473162/55837445-09362780-5ae7-11e9-9ee5-da2359de7125.png)

If the 'Update Data Source' operation allowed credentials to be set during deployment, all of these issues go away, and I finally have my true CI / CD across environments.

Thanks, and I appreciate your efforts to build and support this tool

Mark

**Comment by maikvandergaag** [comment]
@Singley : When updating the datasource the account you are using. Must be the owner of the dataset.

I hope to get started on the feature next week, It has been busy times with the birth of my son.

**Comment by Singley** [comment]
@maikvandergaag congratulations!  

Thanks for considering this feature- I'll keep an eye on it moving forward.

**Comment by KateHamster** [comment]
@maikvandergaag Do you know when this feature will be finally available? We are looking forward for it!

**Comment by hoffe86** [comment]
@maikvandergaag We are also interesting in this feature, because we are running our solution in four environments (Development, Integration, Test and Production) with different credentials

**Comment by maikvandergaag** [comment]
Hi Everyone,
Sorry that it has been taking that long had some personal stuff (a new son, and moving between houses) I hope to get it in in the next few weeks.

**Comment by maikvandergaag** [comment]
Sorry for the late response due to some personal stuff I haven't been able to proccess this hope to be able to do this in august

**Comment by larrysteele** [comment]
I'm still looking forward to this feature also. I've actually been working with Microsoft on exactly how to accomplish this, mostly for Odata and passing the token to the dataset to update the credentials using PowerShell. The PS logic appears to work but invalidates the report. I'm hoping to have a resolution shortly with them. Any help you could provide would be amazing and I think most of us would be interested in Odata and SQL auth as they seem to be the most common forms of the Dataset.

**Comment by maikvandergaag** [comment]
Hi Larry, thank you for your message, I hope to add some things this week. 
The way it be working is via a connection string or are you looking for a different solution?

**Comment by michaelgoconnor** [comment]
Hi @maikvandergaag Just wondering if you have any update on this feature massively appreciate the effort you have put in here.

**Comment by maikvandergaag** [comment]
I have added the functionality in the beta version. Are you able to test?

**Comment by michaelgoconnor** [comment]
@maikvandergaag Sadly i ended up not using the component and i don't access to environment where I to test anymore, sorry

**Comment by Singley** [comment]
I'm out of the country for a week with no access to my work environments.
I'll be happy to test upon my return.  Thanks!

**Comment by maikvandergaag** [comment]
If you send me your organization is I will give you access to the beta.

Groetjes,

Maik van der Gaag

________________________________

**Comment by MartinWa** [comment]
I am looking for this feature and I could help test it.

**Comment by maikvandergaag** [comment]
If you send your organization id of Azure DevOps I can add you to the beta

Groetjes,

Maik van der Gaag

________________________________

**Comment by MartinWa** [comment]
I have done some testing with the beta. I do the following three steps:
```
steps:
- task: Development-vanderGaag.maikvandergaag-power-bi-actionsDev.PowerBIActions.PowerBIActions@4
  displayName: 'Power BI Action: Publish'
  inputs:
    serviceConnection: PowerBi
    WorkspaceName: 'Embedded-Dev'
    PowerBIPath: '$(System.DefaultWorkingDirectory)/Statistics-CD/PowerBiReports/basic.pbix'
```
```
steps:
- task: Development-vanderGaag.maikvandergaag-power-bi-actionsDev.PowerBIActions.PowerBIActions@4
  displayName: 'Power BI Action: UpdateDatasource'
  inputs:
    serviceConnection: PowerBi
    Action: UpdateDatasource
    WorkspaceName: 'Embedded-Dev'
    DatasetName: basic
    OldServer: 'xxx.database.windows.net'
    NewServer: 'yyy.database.windows.net'
    OldDatabase: 'zzz'
    NewDatabase: 'ttt'
```
```
steps:
- task: Development-vanderGaag.maikvandergaag-power-bi-actionsDev.PowerBIActions.PowerBIActions@4
  displayName: 'Power BI Action: SQLDirect'
  inputs:
    serviceConnection: PowerBi
    Action: SQLDirect
    WorkspaceName: 'Embedded-Dev'
    DatasetName: basic
    ConnectionString: 'Data Source=yyy.database.windows.net;Initial Catalog=ttt;User ID=sss;Password=uuu'
```

When I run the first time (no report in Power BI) I get the following error:
`Dataset doesn't contain a datasource that matches selector #1`
If I re-run without deleting the report it works.

The above works for Service Principal. I have also tested with User Principal but then I get:
`Exception calling "GetResult" with "0" argument(s): "AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.`
Perhaps I have configured the User Principal wrong?

In any case the SQLDirect step seems to work fine (verified by calling the Get Datasources API).
